
research_task:
  description: >
    You are tasked with ACCOMPLISHING THE FOLLOWING SCAN {target}. You are known for your ability to find vulnerabilities in websites, using either tools nmap or owasp zap or dirbuster tool or sqlmap tool or metasploit tool or sublist3r tool or whois tool depending on what the user chooses.
    
  expected_output: >
    a scan results on the website using the options described {target} 
  agent: researcher

telegram_task:
  description: >
    Send the document with the results of the scan requested by the user to the user via Telegram. 
    The agent must determine which scan(s) the user requested and send only the corresponding file(s):
    
    - If the user requested **only an Nmap scan**, send the file located at:
      `D:\Stage_PFE\CrewAI\crewai_project\nmap_report.txt`.
    
    - If the user requested **only an OWASP ZAP scan**, send the file located at:
      `D:\Stage_PFE\CrewAI\crewai_project\zap_report.html`.
    - If the user requested **only an dirbuster scan**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\dirbuster_report.txt
    - If the user requested **only an sqlmap scan**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\sqlmap_report.txt
    - If the user requested **only an ssl scanner**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\ssl_report.txt       
    - If the user requested **only an Sublist3r**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\Sublist3r_report.txt 
    - If the user requested **only an whois tool**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\whois_report.txt 
    - If the user requested **only an dnsrecon tool**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\dnsrecon_report.txt 
    - If the user requested **only an scrapy tool**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\scrapy_report.json 
    - If the user requested **only an wafw00f tool**, send the file located at:
       D:\Stage_PFE\CrewAI\crewai_project\wafw00f_report.txt 
    
    - If the user requested OTHER COMBINATIONS, send THE files RELEVANT TO WHAT THE USER REQUESTED:
      `D:\Stage_PFE\CrewAI\crewai_project\nmap_report.txt` and
      `D:\Stage_PFE\CrewAI\crewai_project\zap_report.html`and
      'D:\Stage_PFE\CrewAI\crewai_project\dirbuster_report.txt' and
      'D:\Stage_PFE\CrewAI\crewai_project\sqlmap_report.txt' 
      'D:\Stage_PFE\CrewAI\crewai_project\ssl_report.txt'   
      'D:\Stage_PFE\CrewAI\crewai_project\Sublist3r_report.txt' 
      'D:\Stage_PFE\CrewAI\crewai_project\whois_report.txt '
      'D:\Stage_PFE\CrewAI\crewai_project\dnsrecon_report.txt '
      'D:\Stage_PFE\CrewAI\crewai_project\scrapy_report.json '
      'D:\Stage_PFE\CrewAI\crewai_project\wafw00f_report.txt'

    
    The agent must **not send any files** for scans that were not explicitly requested by the user.
  expected_output: >
    A message sent to the user via Telegram containing the results of the scan(s) they requested.
    The message should clearly indicate which scan results are being shared.
  agent: telegram_result_sender

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
